name: "Show sccache Stats"
description: "Display sccache statistics and report cache performance metrics"
outputs:
  cache-hit-rate:
    description: "The cache hit rate percentage"
    value: ${{ steps.stats.outputs.cache-hit-rate }}
  compile-requests:
    description: "Total compile requests"
    value: ${{ steps.stats.outputs.compile-requests }}
  cache-hits:
    description: "Number of cache hits"
    value: ${{ steps.stats.outputs.cache-hits }}
  cache-misses:
    description: "Number of cache misses"
    value: ${{ steps.stats.outputs.cache-misses }}
  cache-size:
    description: "Current cache size"
    value: ${{ steps.stats.outputs.cache-size }}

runs:
  using: "composite"
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Cache Bun
      uses: actions/cache@v4
      with:
        path: |
          ~/.bun/install/cache
          scripts/node_modules
        key: ${{ runner.os }}-bun-scripts-${{ hashFiles('scripts/bun.lock') }}
        restore-keys: |
          ${{ runner.os }}-bun-scripts-

    - name: Install Scripts Dependencies
      shell: bash
      working-directory: scripts
      run: bun install --frozen-lockfile

    - name: Show sccache Stats
      id: stats
      shell: bash
      working-directory: scripts
      run: bun run main.ts sccache-stats
