name = "collects"
compatibility_date = "2025-05-05"
main = "./worker/index.ts"
routes = [{ pattern = "collects.lqxclqxc.com", custom_domain = true }]
workers_dev = false

[assets]
directory = "./dist"
binding = "ASSETS"

[env.preview]
workers_dev = false
routes = [{ pattern = "*.collects-preview.lqxclqxc.com", custom_domain = true }]
