import { readFileSync } from "fs";

/**
 * Valid conventional commit types
 */
const VALID_TYPES = [
  "feat",
  "fix",
  "docs",
  "style",
  "refactor",
  "perf",
  "test",
  "build",
  "ci",
  "chore",
  "revert",
] as const;

type CommitType = (typeof VALID_TYPES)[number];

/**
 * Conventional commit pattern
 * Format: <type>[optional scope]: <description>
 */
const COMMIT_PATTERN =
  /^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\([a-zA-Z0-9_-]+\))?: .+/;

/**
 * Result of commit message validation
 */
export interface CommitMsgValidationResult {
  valid: boolean;
  subject: string;
  error?: string;
}

/**
 * Type descriptions for help text
 */
const TYPE_DESCRIPTIONS: Record<CommitType, string> = {
  feat: "A new feature",
  fix: "A bug fix",
  docs: "Documentation only changes",
  style: "Changes that do not affect code meaning (formatting, etc.)",
  refactor: "Code change that neither fixes a bug nor adds a feature",
  perf: "A code change that improves performance",
  test: "Adding missing tests or correcting existing tests",
  build: "Changes affecting build system or external dependencies",
  ci: "Changes to CI configuration files and scripts",
  chore: "Other changes that don't modify src or test files",
  revert: "Reverts a previous commit",
};

/**
 * Read commit message from file
 */
export function readCommitMessage(source: string): string {
  return readFileSync(source, "utf-8");
}

/**
 * Validates a commit message against conventional commit format
 */
export function validateCommitMessage(
  commitMsg: string,
): CommitMsgValidationResult {
  // Extract the first line (subject) of the commit message
  const subject = commitMsg.split("\n")[0].trim();

  // Skip validation for merge commits
  if (subject.startsWith("Merge ")) {
    return { valid: true, subject };
  }

  // Skip validation for revert commits generated by git
  if (subject.startsWith('Revert "')) {
    return { valid: true, subject };
  }

  // Validate the commit message
  if (COMMIT_PATTERN.test(subject)) {
    return { valid: true, subject };
  }

  return {
    valid: false,
    subject,
    error: "Invalid commit message format",
  };
}

/**
 * Generates error message for invalid commit
 */
export function formatErrorMessage(subject: string): string {
  const lines = [
    "ERROR: Invalid commit message format!",
    "",
    "Your commit message:",
    `  ${subject}`,
    "",
    "Expected format: <type>[optional scope]: <description>",
    "",
    "Valid types:",
  ];

  for (const type of VALID_TYPES) {
    lines.push(`  ${type.padEnd(10)}: ${TYPE_DESCRIPTIONS[type]}`);
  }

  lines.push("");
  lines.push("Examples:");
  lines.push("  feat: add user authentication");
  lines.push("  fix(ui): resolve button alignment issue");
  lines.push("  docs: update README with installation instructions");
  lines.push("");

  return lines.join("\n");
}

/**
 * Main function to run commit message validation
 */
export function runCommitMsgCheck(source: string): void {
  const commitMsg = readCommitMessage(source);
  const result = validateCommitMessage(commitMsg);

  if (result.valid) {
    process.exit(0);
  }

  console.error(formatErrorMessage(result.subject));
  process.exit(1);
}
