macro_rules! register_state_id {
{$($id:ident),*$(,)*} => {
pub mod state_id {
    //! Auto-generated StateID enum and associated functions.
    //!
    //! This module is generated by the `registerState!` macro in `register_states.rs`.
    //! It defines the `StateID` enum and provides utility functions for working with it.
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
    #[repr(usize)]
    pub enum StateID {
    $($id,)+
    }

    const LEN:usize = [$(StateID::$id,)+].len();
    const STATE_ID_ARRAY: [StateID; LEN] = [$(StateID::$id,)+];
    const STATE_ID_STRING: [&'static str; LEN] = [$(stringify!($id),)+];
    const STATE_ID_LENGTHS: [usize; LEN] = [$(stringify!($id).len(),)+];

    impl StateID {
    #[inline]
    pub const fn id_len(&self) -> usize {
        STATE_ID_LENGTHS[*self as usize]
    }
    #[inline]
    pub const fn is_empty(&self) -> bool {
        false
    }
    #[inline]
    pub const fn get_all() -> &'static [StateID] {
        &STATE_ID_ARRAY
    }
    #[inline]
    pub const fn amount() -> usize {
        LEN
    }
    }

    impl Default for StateID {
    #[inline]
    fn default() -> Self {
        STATE_ID_ARRAY[0]
    }
    }

    impl TryFrom<usize> for StateID {
    type Error = usize;
    fn try_from(value: usize) -> Result<Self, Self::Error> {
        if value < LEN {
            Ok(STATE_ID_ARRAY[value])
        } else {
            Err(value)
        }
    }
    }

    impl<'a> TryFrom<&'a str> for StateID {
    type Error = &'a str;
    fn try_from(value: &'a str) -> Result<Self, Self::Error> {
        match value {
            $(
                stringify!($id) => Ok(Self::$id),
            )+
            _ => Err(value)
        }
    }
    }

    impl Into<&'static str> for StateID {
    fn into(self) -> &'static str {
        STATE_ID_STRING[self as usize]
    }
    }

    impl Into<usize> for StateID {
    fn into(self) -> usize {
        self as usize
    }
    }

    impl ToString for StateID {
    #[inline]
    fn to_string(&self) -> String {
        STATE_ID_STRING[*self as usize].to_string()
    }
    }
}
};
}

register_state_id! {
    None,
    ApiStatus
}
