macro_rules! reg{
{$($id:ident),*$(,)*} => {
pub mod reg {
    //! Auto-generated StateID enum and associated functions.
    //!
    //! This module is generated by the `registerState!` macro in `register_states.rs`.
    //! It defines the `StateID` enum and provides utility functions for working with it.
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
    #[repr(usize)]
    pub enum Reg {
    $($id,)+
    }

    use std::fmt;

    const LEN:usize = [$(Reg::$id,)+].len();
    const REG_ARRAY: [Reg; LEN] = [$(Reg::$id,)+];
    const REG_STRING: [&'static str; LEN] = [$(stringify!($id),)+];
    const REG_LENGTHS: [usize; LEN] = [$(stringify!($id).len(),)+];

    impl Reg {
    #[inline]
    pub const fn id_len(&self) -> usize {
        REG_LENGTHS[*self as usize]
    }
    #[inline]
    pub const fn is_empty(&self) -> bool {
        false
    }
    #[inline]
    pub const fn get_all() -> &'static [Reg] {
        &REG_ARRAY
    }
    #[inline]
    pub const fn amount() -> usize {
        LEN
    }
    }

    impl Default for Reg {
    #[inline]
    fn default() -> Self {
        REG_ARRAY[0]
    }
    }

    impl TryFrom<usize> for Reg {
    type Error = usize;
    fn try_from(value: usize) -> Result<Self, Self::Error> {
        if value < LEN {
            Ok(REG_ARRAY[value])
        } else {
            Err(value)
        }
    }
    }

    impl<'a> TryFrom<&'a str> for Reg {
    type Error = &'a str;
    fn try_from(value: &'a str) -> Result<Self, Self::Error> {
        match value {
            $(
                stringify!($id) => Ok(Self::$id),
            )+
            _ => Err(value)
        }
    }
    }

    impl From<Reg> for &str {
    fn from(value: Reg) -> Self {
        REG_STRING[value as usize]
    }
    }

    impl From<Reg> for usize {
    fn from(value: Reg) -> usize {
        value as usize
    }
    }

    impl fmt::Display for Reg {
    #[inline]
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", REG_STRING[*self as usize])
    }
    }
}
};
}

reg! {
    ApiStatus
}
