name: 'Scheduled Job Issue Creator'
description: 'Create GitHub issue when a scheduled job fails'
inputs:
  github-token:
    description: 'GitHub token with issues:write permission'
    required: true
  workflow-name:
    description: 'Name of the failed workflow'
    required: true
  workflow-run-id:
    description: 'ID of the failed workflow run'
    required: true
  workflow-run-url:
    description: 'URL to the failed workflow run'
    required: true
  head-sha:
    description: 'Git SHA of the commit that triggered the workflow'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Cache Bun
      uses: actions/cache@v4
      with:
        path: |
          ~/.bun/install/cache
          scripts/node_modules
        key: ${{ runner.os }}-bun-scripts-${{ hashFiles('scripts/bun.lock') }}
        restore-keys: |
          ${{ runner.os }}-bun-scripts-

    - name: Install Scripts Dependencies
      shell: bash
      working-directory: scripts
      run: bun install --frozen-lockfile

    - name: Create Issue for Scheduled Job Failure
      shell: bash
      working-directory: scripts
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        WORKFLOW_RUN_ID: ${{ inputs.workflow-run-id }}
        WORKFLOW_NAME: ${{ inputs.workflow-name }}
        WORKFLOW_RUN_URL: ${{ inputs.workflow-run-url }}
        HEAD_SHA: ${{ inputs.head-sha }}
      run: bun run main.ts scheduled-job-issue
