name: 'Scheduled Job Issue Creator'
description: |
  Create GitHub issue when a scheduled job fails. 
  Use as a post-job step with `if: failure() && github.event_name == 'schedule'`.
  This action uses GitHub context to get workflow information (run_id, workflow name, etc.).
inputs:
  github-token:
    description: 'GitHub token with issues:write permission'
    required: true
  job-name:
    description: 'Display name of the failed job (the "name:" value in the workflow YAML). Used to filter logs to specific job.'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Cache Bun
      uses: actions/cache@v4
      with:
        path: |
          ~/.bun/install/cache
          scripts/node_modules
        key: ${{ runner.os }}-bun-scripts-${{ hashFiles('scripts/bun.lock') }}
        restore-keys: |
          ${{ runner.os }}-bun-scripts-

    - name: Install Scripts Dependencies
      shell: bash
      working-directory: scripts
      run: bun install --frozen-lockfile

    - name: Create Issue for Scheduled Job Failure
      shell: bash
      working-directory: scripts
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        WORKFLOW_RUN_ID: ${{ github.run_id }}
        WORKFLOW_NAME: ${{ github.workflow }}
        WORKFLOW_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        HEAD_SHA: ${{ github.sha }}
        JOB_NAME: ${{ inputs.job-name }}
      run: bun run main.ts scheduled-job-issue
