#!/bin/bash
# Script to validate conventional commit message format
# Usage: ./check-commit-msg.sh <commit-message-file>
#        ./check-commit-msg.sh --stdin (reads from stdin)

set -e

# Conventional commit pattern
# Format: <type>[optional scope]: <description>
# Types: feat, fix, docs, style, refactor, perf, test, build, ci, chore, revert
PATTERN="^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\([a-zA-Z0-9_-]+\))?: .+"

# Get commit message
if [ "$1" = "--stdin" ]; then
    COMMIT_MSG=$(cat)
elif [ -n "$1" ]; then
    COMMIT_MSG=$(cat "$1")
else
    echo "Usage: $0 <commit-message-file> or $0 --stdin"
    exit 1
fi

# Extract the first line (subject) of the commit message
SUBJECT=$(echo "$COMMIT_MSG" | head -n1)

# Skip validation for merge commits
if echo "$SUBJECT" | grep -qE "^Merge "; then
    exit 0
fi

# Skip validation for revert commits generated by git
if echo "$SUBJECT" | grep -qE "^Revert \""; then
    exit 0
fi

# Validate the commit message
if echo "$SUBJECT" | grep -qE "$PATTERN"; then
    exit 0
else
    echo "ERROR: Invalid commit message format!"
    echo ""
    echo "Your commit message:"
    echo "  $SUBJECT"
    echo ""
    echo "Expected format: <type>[optional scope]: <description>"
    echo ""
    echo "Valid types:"
    echo "  feat:     A new feature"
    echo "  fix:      A bug fix"
    echo "  docs:     Documentation only changes"
    echo "  style:    Changes that do not affect code meaning (formatting, etc.)"
    echo "  refactor: Code change that neither fixes a bug nor adds a feature"
    echo "  perf:     A code change that improves performance"
    echo "  test:     Adding missing tests or correcting existing tests"
    echo "  build:    Changes affecting build system or external dependencies"
    echo "  ci:       Changes to CI configuration files and scripts"
    echo "  chore:    Other changes that don't modify src or test files"
    echo "  revert:   Reverts a previous commit"
    echo ""
    echo "Examples:"
    echo "  feat: add user authentication"
    echo "  fix(ui): resolve button alignment issue"
    echo "  docs: update README with installation instructions"
    echo ""
    exit 1
fi
