name: Deploy to Cloudflare Pages

on:
  # Triggered on pushes to main branch
  push:
    branches:
      - main
  # Also run on pull requests
  pull_request:
    branches:
      - main
  # Also run on Tag created
  push:
    tags:
      - "*"
  # Allow manual triggering
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to Cloudflare Pages
permissions:
  contents: read
  deployments: write

jobs:
  # Build for wasm and deploy to Cloudflare Pages
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: wasm32-unknown-unknown

      - name: Install trunk
        run: |
          wget -qO- https://github.com/thedodd/trunk/releases/latest/download/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
          sudo mv trunk /usr/local/bin/

      - name: Build with Trunk
        run: trunk build --release
        env:
          # For Cloudflare Pages, we don't need a public URL prefix
          public_url: ""

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: collects
          directory: dist
          # Optional: Enable this if you want to have GitHub Deployments triggered
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          # Optional: Switch what branch you want to deploy to. Useful for testing.
          branch: ${{ github.event.pull_request.head.ref || github.head_ref || github.ref_name }}
          # Optional: Change the wrangler version
          wranglerVersion: '3'